---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Lint/EmptyBlock:
  Exclude:
  - lib/tasks/eac_rails_base0.rake
Lint/UselessMethodDefinition:
  Exclude:
  - lib/eac_rails_base0/x_engine.rb
Metrics/AbcSize:
  Exclude:
  - lib/eac_rails_base0/app_base/application/development.rb
  - lib/eac_rails_base0/app_base/application/production.rb
RSpec/Rails/InferredSpecType:
  Exclude:
  - spec/features/current_user_spec.rb
Rails/FilePath:
  Exclude:
  - lib/eac_rails_base0/app_base/application/all.rb
Rails/I18nLocaleTexts:
  Exclude:
  - app/controllers/eac_rails_base0/application_controller.rb
Style/HashAsLastArrayItem:
  Exclude:
  - app/helpers/eac_rails_base0/user_menu_helper.rb
Style/MapToHash:
  Exclude:
  - app/controllers/eac_rails_base0/mailer_controller.rb
Style/RedundantFileExtensionInRequire:
  Exclude:
  - lib/eac_rails_base0/app_generator/templates/config/application.rb
  - spec/support/rails_app_append/config/application.rb
Style/RedundantInitialize:
  Exclude:
  - lib/eac_rails_base0/x_engine.rb
Style/StringConcatenation:
  Exclude:
  - exe/eac_rails_base0_app
