# frozen_string_literal: true

source 'https://rubygems.org'

gem 'eac_rails_base0'

group :development, :test do
  gem 'quiet_assets'
end

group :production do
  gem 'rails_12factor'
end

# Gems locais
Dir["#{__dir__}/{vendor/gems,engines}/*/*.gemspec"].each do |file|
  gem ::File.basename(::File.dirname(file)), path: ::File.dirname(file)
end
