# frozen_string_literal: true

source 'https://rubygems.org'

gem 'eac_rails_base0'

group :development, :test do
  gem 'quiet_assets'
end

group :production do
  gem 'rails_12factor'
end

# Gems locais
require_relative 'lib/local_plugins'
LocalPlugins.plugins.each do |p|
  gem p.name, path: p.root
end
